version: '3.8'

services:

  weather:
    build:
      context: 'git@github.com:rodion73/Demo.Elastic.git#develop'
      dockerfile: 'src/Demo.Elastic.Weather/Dockerfile'
    container_name: demo-elastic-weather
    ports:
    - '80:80'
    - '443:443'
    environment: 
    - 'ASPNETCORE_URLS=https://+:443;http://+:80'
    - 'ASPNETCORE_Kestrel__Certificates__Default__Path=skaro.ddns.net.pfx'
    - 'ASPNETCORE_Kestrel__Certificates__Default__Password=P@ssw0rd'
    volumes: 
    - './skaro.ddns.net.pfx:/app/skaro.ddns.net.pfx:ro'
