version: '3.8'
services:
  weather:
    build:
      context: 'git@github.com:rodion73/Demo.Elastic.git#develop'
      dockerfile: 'src/Demo.Elastic.Weather/Dockerfile'
    container_name: demo-elastic-weather
    ports:
    - '80:80'
    - '443:443'
